/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Faqs = {
  _id: string;
  _type: "faqs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  faqItems?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  content?: BlockContent;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<
        | {
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }
        | ({
            _key: string;
          } & IconManager)
      >;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & IconManager)
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LegalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "legal";
};

export type SiteConfig = {
  _id: string;
  _type: "siteConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  twitterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  phoneNumbers?: Array<{
    number?: string;
    label?: string;
    _key: string;
  }>;
  emails?: Array<{
    email?: string;
    label?: string;
    _key: string;
  }>;
  address?: {
    street?: string;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
  };
  sitetiming?: string;
  socialMedia?: Array<{
    platform?:
      | "twitter"
      | "youtube"
      | "instagram"
      | "facebook"
      | "whatsapp"
      | "linkedin";
    url?: string;
    label?: string;
    _key: string;
  }>;
  footerLegalLinks?: Array<
    {
      _key: string;
    } & LegalReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type IconManager = {
  _type: "icon.manager";
  icon?: string;
  metadata?: IconManagerMetadata;
};

export type IconManagerMetadata = {
  _type: "icon.manager.metadata";
  downloadUrl?: string;
  url?: string;
  inlineSvg?: string;
  collectionId?: string;
  collectionName?: string;
  iconName?: string;
  palette?: boolean;
  license?: IconManagerLicense;
  author?: IconManagerAuthor;
  size?: IconManagerSize;
  hFlip?: boolean;
  vFlip?: boolean;
  rotate?: number;
  color?: IconManagerColor;
};

export type IconManagerColor = {
  _type: "icon.manager.color";
  hex?: string;
  rgba?: IconManagerColorRgba;
};

export type IconManagerSize = {
  _type: "icon.manager.size";
  width?: number;
  height?: number;
};

export type IconManagerAuthor = {
  _type: "icon.manager.author";
  name?: string;
  url?: string;
};

export type IconManagerLicense = {
  _type: "icon.manager.license";
  name?: string;
  url?: string;
};

export type IconManagerColorRgba = {
  _type: "icon.manager.color.rgba";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Faqs
  | Legal
  | SanityImageAssetReference
  | BlockContent
  | Slug
  | LegalReference
  | SiteConfig
  | SanityImageCrop
  | SanityImageHotspot
  | IconManager
  | IconManagerMetadata
  | IconManagerColor
  | IconManagerSize
  | IconManagerAuthor
  | IconManagerLicense
  | IconManagerColorRgba
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;
