/**
 * Type definition for Sanity Icon Manager
 * This is a minimal type definition for the icon manager plugin
 * The full types will be generated by running: pnpm generate:types
 */

export interface IconManager {
  _type: "icon.manager";
  icon?: string;
  metadata?: {
    iconName?: string;
    collectionId?: string;
    collectionName?: string;
    hFlip?: boolean;
    vFlip?: boolean;
    rotate?: number;
    size?: {
      width: number;
      height: number;
    };
    color?: {
      hex: string;
    };
    inlineSvg?: string;
  };
}
